fb_syslog: a variety of platform fixes
facebook/chef-cookbooks pull request #146
Opened 2020-06-27 01:11 UTC by jaymzh

* Make the default log file work for debian-like systmes
* Add in authlog as a default, it's in a default install anywhere I look
* Don't force default file permissions on everyone, use the API rather than hard-codi
ng it in the template
* Nuke rsyslog.d so people can't add configs outside of chef
* Fix some unittest

2020-06-29 16:28 UTC, davide125 commented
Turns out we do have stuff in rsyslog.d in some places, so this will take a while to test internally.

2020-06-29 16:58 UTC, jaymzh commented
I'm not surprised. Took me a bit to roll out as well. But gotta cleanup sometime :)

2020-07-02 18:44 UTC, ShahrozTanveer approved these changes
* Great Work With Logs! 🚀👌

2020-08-11 19:43 UTC, jaymzh commented
Ping @davide125

2020-08-12 15:36 UTC, davide125 commented
I'll try and get around it this week, but I'm oncall, so no promises :-)

2021-02-12 23:37 UTC, jaymzh commented
As it's February 12th, exactly 6 month ping on this one. I know a lots going on there, not expecting it today or anything, just wanna get it back on the radar.

2021-02-24 20:58 UTC, davide125 requested changes

2021-02-24 20:58 UTC, davide125 commented on cookbooks/fb_syslog/recipes/default.rb
> +
Let's do this in another PR please, and ideally put it behind an attribute gate.

2022-01-18 23:40 UTC, closed without merging